services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    command: yarn dev -p 3000
    ports:
      - "3000:3000"
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3001"
    volumes:
      - ./back:/app
    depends_on:
      - db
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test_db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_test
    ports:
      - "5433:5433"
volumes:
  front_node_modules:
  postgres_data:
